apiVersion: v2
name: sda-db
version: 0.7.6
appVersion: v0.2.48
description: Database component for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sensitive-data-archive
