apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "sda.fullname" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $postgresPassword := (get $secretData "postgresPassword") | default (include "adminPass" . ) }}
  postgresPassword: {{ $postgresPassword | quote }}
