{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-finalize
type: Opaque
data:
  dbPassword: {{ required "DB password is required" (include "dbPassFinalize" .) | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUserFinalize" .) | b64enc }}
  mqPassword: {{ required "MQ password is required" (include "mqPassFinalize" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserFinalize" .) | b64enc }}
{{- end }}
{{- end }}
