{{- if eq "federated".Values.global.schemaType }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-intercept
type: Opaque
data:
  mqPassword: {{ required "MQ password is required" (include "mqPassInterceptor" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserInterceptor" .) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
