{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-mapper
type: Opaque
data:
  dbPassword: {{ required "DB password is required" (include "dbPassMapper" .) | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUserMapper" .) | b64enc }}
  mqPassword: {{ required "MQ password is required" (include "mqPassMapper" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserMapper" .) | b64enc }}
{{- end }}
{{- end }}
