{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if eq "s3" .Values.global.inbox.storageType }}
{{- if not .Values.global.vaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox
type: Opaque
data:
  dbPassword: {{ required "DB password is required" (include "dbPassInbox" .) | quote | trimall "\"" | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUserInbox" .) | b64enc }}
  mqPassword: {{ required "MQ password is required" (include "mqPassInbox" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserInbox" .) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
