{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if and (eq "posix" .Values.global.inbox.storageType) .Values.global.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox
type: Opaque
data:
  mqPassword: {{ required "MQ password is required" (include "mqPassInbox" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserInbox" .) | b64enc }}
  cegaCredentials: {{ printf "%s:%s" (required "CEGA nss user is missing" .Values.global.cega.user) (required "CEGA nss user is missing" .Values.global.cega.password) | quote | trimall "\"" | b64enc }}
{{- end }}
{{- end }}
