{{- if not .Values.global.vaultSecrets }}
{{- if eq "s3" .Values.global.archive.storageType }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3archive-keys
type: Opaque
data:
  s3ArchiveAccessKey: {{ required "Accesskey required for archive" .Values.global.archive.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3ArchiveSecretKey: {{ required "Secretkey required for archive" .Values.global.archive.s3SecretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- if eq "s3" .Values.global.backupArchive.storageType }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3backup-keys
type: Opaque
data:
  s3BackupAccessKey: {{ required "Accesskey required for backupArchive" .Values.global.backupArchive.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3BackupSecretKey: {{ required "Secretkey required for backupArchive" .Values.global.backupArchive.s3SecretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- if eq "s3" .Values.global.inbox.storageType }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-s3inbox-keys
type: Opaque
data:
  s3InboxAccessKey: {{ required "Accesskey required for inbox" .Values.global.inbox.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3InboxSecretKey: {{ required "Secretkey required for inbox" .Values.global.inbox.s3SecretKey | quote | trimall "\"" | b64enc }}
{{- end }}
{{- end }}
