{{- if eq "isolated" .Values.global.schemaType }}
{{- if ne "" .Values.global.sync.remote.host }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-sync
  labels:
    role: sync
    app: {{ template "sda.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-sync
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.name" . }}-sync
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.name" . }}-sync
        role: sync
        release: {{ .Release.Name }}
      annotations:
  {{- if not .Values.global.vaultSecrets }}
        checksum/config: {{ include (print $.Template.BasePath "/sync-secrets.yaml") . | sha256sum }}
  {{- end }}
  {{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
  {{- end }}
  {{- if .Values.sync.annotations }}
{{- toYaml .Values.sync.annotations | nindent 8 -}}
  {{- end }}
    spec:
  {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
  {{- end }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
  {{- if and .Values.global.pkiPermissions .Values.global.tls.enabled }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 65534:65534 /tls/* && chmod 0600 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
    {{- if .Values.global.extraSecurityContext }}
{{- toYaml .Values.global.extraSecurityContext | nindent 10 -}}
    {{- end }}
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
  {{- end }}
      containers:
      - name: sync
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["sda-sync"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: "RuntimeDefault"
        env:
        - name: ARCHIVE_TYPE
  {{- if eq "s3" .Values.global.archive.storageType }}
          value: "s3"
        - name: ARCHIVE_URL
          value: {{ required "S3 archive URL missing" .Values.global.archive.s3Url }}
      {{- if .Values.global.archive.s3Port }}
        - name: ARCHIVE_PORT
          value: {{ .Values.global.archive.s3Port | quote }}
      {{- end }}
        - name: ARCHIVE_BUCKET
          value: {{ required "S3 archive bucket missing" .Values.global.archive.s3Bucket }}
        - name: ARCHIVE_REGION
          value: {{ default "us-east-1" .Values.global.archive.s3Region }}
        - name: ARCHIVE_CHUNKSIZE
          value: {{ .Values.global.archive.s3ChunkSize | quote }}
    {{- if and .Values.global.archive.s3CaFile .Values.global.tls.enabled }}
        - name: ARCHIVE_CACERT
          value: {{ template "tlsPath" . }}/ca.crt
    {{- end }}
  {{- else }}
          value: "posix"
        - name: ARCHIVE_LOCATION
          value: "{{ .Values.global.archive.volumePath }}"
  {{- end }}
        - name: SYNC_CENTERPREFIX
          value: {{ .Values.global.sync.centerPrefix}}
        - name: SYNC_DESTINATION_TYPE
  {{- if eq "s3" .Values.global.sync.destination.storageType }}
          value: "s3"
        - name: SYNC_DESTINATION_URL
          value: {{ required "S3 sync archive URL missing" .Values.global.sync.destination.s3Url }}
      {{- if .Values.global.sync.destination.s3Port }}
        - name: SYNC_DESTINATION_PORT
          value: {{ .Values.global.sync.destination.s3Port | quote }}
      {{- end }}
        - name: SYNC_DESTINATION_BUCKET
          value: {{ required "S3 sync archive bucket missing" .Values.global.sync.destination.s3Bucket }}
        - name: SYNC_DESTINATION_REGION
          value: {{ default "us-east-1" .Values.global.sync.destination.s3Region }}
        - name: SYNC_DESTINATION_CHUNKSIZE
          value: {{ .Values.global.sync.destination.s3ChunkSize | quote }}
    {{- if and .Values.global.sync.destination.s3CaFile .Values.global.tls.enabled }}
        - name: SYNC_DESTINATION_CACERT
          value: {{ template "tlsPath" . }}/ca.crt
    {{- end }}
  {{- end }}
        - name: C4GH_FILEPATH
          value: "{{ template "c4ghPath" . }}/{{ .Values.global.c4gh.keyFile }}"
        - name: C4GH_SYNCPUBKEYPATH
          value: "{{ template "c4ghPath" . }}/{{ .Values.global.c4gh.syncPubKey }}"
        - name: BROKER_EXCHANGE
          value: {{ default "sda" .Values.global.broker.exchange }}
        - name: BROKER_QUEUE
          value: {{ default "mapping_stream" .Values.global.sync.brokerQueue }}
        - name: BROKER_HOST
          value: {{ required "A valid MQ host is required" .Values.global.broker.host | quote }}
        - name: BROKER_PORT
          value: {{ .Values.global.broker.port | quote }}
        - name: BROKER_PREFETCHCOUNT
          value: {{ .Values.global.broker.prefetchCount | quote }}
        - name: BROKER_VHOST
          value: {{ .Values.global.broker.vhost | quote }}
        - name: BROKER_SERVERNAME
          value: {{ .Values.global.broker.host | quote }}
        - name: BROKER_SSL
          value: {{ .Values.global.tls.enabled | quote }}
    {{- if .Values.global.tls.enabled }}
        - name: BROKER_VERIFYPEER
          value: {{ .Values.global.broker.verifyPeer | quote }}
        - name: BROKER_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
    {{- if .Values.global.broker.verifyPeer }}
        - name: BROKER_CLIENTCERT
          value: {{ include "tlsPath" . }}/tls.crt
        - name: BROKER_CLIENTKEY
          value: {{ include "tlsPath" . }}/tls.key
    {{- end }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
        - name: DB_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
    {{- if ne "verify-none" .Values.global.db.sslMode }}
        - name: DB_CLIENTCERT
          value: {{ include "tlsPath" . }}/tls.crt
        - name: DB_CLIENTKEY
          value: {{ include "tlsPath" . }}/tls.key
    {{- end }}
  {{- end }}
        - name: DB_DATABASE
          value: {{ default "sda" .Values.global.db.name | quote }}
        - name: DB_HOST
          value: {{ required "A valid DB host is required" .Values.global.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.global.db.port | quote }}
        - name: DB_SSLMODE
          value: {{ template "dbSSLmode" . }}
      {{- if .Values.global.log.format }}
        - name: LOG_FORMAT
          value: {{ .Values.global.log.format | quote }}
      {{- end }}
      {{- if .Values.global.log.level }}
        - name: LOG_LEVEL
          value: {{ .Values.global.log.level | quote }}
      {{- end }}
        - name: SCHEMA_TYPE
          value: {{ default "isolated" .Values.global.schemaType }}
        - name: SYNC_REMOTE_HOST
          value: {{ .Values.global.sync.remote.host }}
  {{- if not .Values.global.vaultSecrets }}
    {{- if eq "s3" .Values.global.archive.storageType }}
        - name: ARCHIVE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveAccessKey
        - name: ARCHIVE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveSecretKey
    {{- end }}
    {{- if eq "s3" .Values.global.sync.destination.storageType }}
        - name: SYNC_DESTINATION_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-sync
              key: s3AccessKey
        - name: SYNC_DESTINATION_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-sync
              key: s3SecretKey
    {{- end }}
        - name: BROKER_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-sync
                key: mqPassword
        - name: BROKER_USER
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-sync
                key: mqUser
        - name: C4GH_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: {{ required "A secret for the c4gh key is required" .Values.global.c4gh.secretName }}
              key: passphrase
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-sync
                key: dbPassword
        - name: DB_USER
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-sync
                key: dbUser
        - name: SYNC_REMOTE_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-sync
              key: restUser
        - name: SYNC_REMOTE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-sync
              key: restPassword
  {{ else }}
        - name: CONFIGFILE
          value: {{ include "confFile" . }}
  {{- end }}
        resources:
{{ toYaml .Values.sync.resources | trim | indent 10 }}
        volumeMounts:
      {{- if not .Values.global.vaultSecrets }}
          - name: c4gh
            mountPath: {{ template "c4ghPath" . }}
      {{- end }}
  {{- if eq "posix" .Values.global.archive.storageType }}
          - name: archive
            mountPath: {{ .Values.global.archive.volumePath | quote }}
  {{- end }}
  {{- if and (not .Values.global.pkiService) .Values.global.tls.enabled }}
          - name: tls
            mountPath: {{ template "tlsPath" . }}
  {{- end }}
      volumes:
      {{- if and (not .Values.global.pkiService) .Values.global.tls.enabled }}
        - name: tls
        {{- if or .Values.global.tls.clusterIssuer .Values.global.tls.issuer }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-sync-certs
        {{- else if .Values.sync.tls.secretName }}
          secret:
            defaultMode: 0440
            secretName: {{ required "An certificate issuer or a TLS secret name is required for sync" .Values.sync.tls.secretName }}
        {{- end }}
      {{- end }}
    {{- if not .Values.global.vaultSecrets }}
        - name: c4gh
          secret:
            defaultMode: 0440
            secretName: {{ required "A secret for the c4gh key is required" .Values.global.c4gh.secretName }}
            items:
            - key: {{ .Values.global.c4gh.keyFile }}
              path: {{ .Values.global.c4gh.keyFile }}
            - key: {{ .Values.global.c4gh.syncPubKey }}
              path: {{ .Values.global.c4gh.syncPubKey }}
    {{- end }}
  {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
    {{- if .Values.global.archive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.archive.existingClaim }}
    {{- else }}
          nfs:
            server: {{ required "An archive NFS server is required" .Values.global.archive.nfsServer | quote }}
            path: {{ if .Values.global.archive.nfsPath }}{{ .Values.global.archive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
    {{- end }}
  {{- end }}
      restartPolicy: Always
{{- end }}
{{- end }}
{{- end }}
