{{- if and (ne "" .Values.global.sync.api.password) (ne "" .Values.global.sync.api.user) }}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-syncapi
type: Opaque
data:
  mqPassword: {{ required "MQ password is required" (include "mqPassSync" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserSync" .) | b64enc }}
  password: {{ required "Sync API password is required" .Values.global.sync.api.password | b64enc }}
  user: {{ required "Sync API username is required" .Values.global.sync.api.user | b64enc }}
{{- end }}
{{- end }}
{{- end }}
