
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-verify
type: Opaque
data:
  dbPassword: {{ required "DB password is required" (include "dbPassVerify" .) | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUserVerify" .) | b64enc }}
  mqPassword: {{ required "MQ password is required" (include "mqPassVerify" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserVerify" .) | b64enc }}
{{- end }}
{{- end }}
