apiVersion: v2
name: sda-svc
version: 0.22.3
appVersion: v0.2.66
kubeVersion: '>= 1.26.0'
description: Components for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sensitive-data-archive
